/* automatically generated by rust-bindgen 0.60.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct buffer {
    pub pointer: *mut cty::c_void,
    pub size: u64,
    pub internal: [u64; 3usize],
}
extern "C" {
    #[link_name = "\u{1}?create_buffer@fpng@@YAXPEAUbuffer@1@@Z"]
    pub fn create_buffer(buf: *mut buffer);
}
extern "C" {
    #[link_name = "\u{1}?dispose_buffer@fpng@@YAXPEAUbuffer@1@@Z"]
    pub fn dispose_buffer(buf: *mut buffer);
}
extern "C" {
    #[link_name = "\u{1}?fpng_encode_image_to_buffer@fpng@@YA_NPEBXIIIAEAUbuffer@1@I@Z"]
    pub fn fpng_encode_image_to_buffer(
        pImage: *const cty::c_void,
        w: u32,
        h: u32,
        num_chans: u32,
        buf: *mut buffer,
        flags: u32,
    ) -> bool;
}
extern "C" {
    #[link_name = "\u{1}?fpng_decode_buffer@fpng@@YAHPEBXIAEAUbuffer@1@AEAI22I@Z"]
    pub fn fpng_decode_buffer(
        pImage: *const cty::c_void,
        image_size: u32,
        buf: *mut buffer,
        width: *mut u32,
        height: *mut u32,
        channels_in_file: *mut u32,
        desired_channels: u32,
    ) -> cty::c_int;
}
