/* automatically generated by rust-bindgen 0.60.1 */

extern "C" {
    #[link_name = "\u{1}?fpng_init@fpng@@YAXXZ"]
    pub fn fpng_init();
}
extern "C" {
    #[link_name = "\u{1}?fpng_cpu_supports_sse41@fpng@@YA_NXZ"]
    pub fn fpng_cpu_supports_sse41() -> bool;
}
pub const FPNG_CRC32_INIT: u32 = 0;
extern "C" {
    #[link_name = "\u{1}?fpng_crc32@fpng@@YAIPEBX_KI@Z"]
    pub fn fpng_crc32(pData: *const cty::c_void, size: usize, prev_crc32: u32) -> u32;
}
pub const FPNG_ADLER32_INIT: u32 = 1;
extern "C" {
    #[link_name = "\u{1}?fpng_adler32@fpng@@YAIPEBX_KI@Z"]
    pub fn fpng_adler32(pData: *const cty::c_void, size: usize, adler: u32) -> u32;
}
pub const FPNG_ENCODE_SLOWER: _bindgen_ty_1 = 1;
pub const FPNG_FORCE_UNCOMPRESSED: _bindgen_ty_1 = 2;
pub type _bindgen_ty_1 = cty::c_int;
pub const FPNG_DECODE_SUCCESS: _bindgen_ty_2 = 0;
pub const FPNG_DECODE_NOT_FPNG: _bindgen_ty_2 = 1;
pub const FPNG_DECODE_INVALID_ARG: _bindgen_ty_2 = 2;
pub const FPNG_DECODE_FAILED_NOT_PNG: _bindgen_ty_2 = 3;
pub const FPNG_DECODE_FAILED_HEADER_CRC32: _bindgen_ty_2 = 4;
pub const FPNG_DECODE_FAILED_INVALID_DIMENSIONS: _bindgen_ty_2 = 5;
pub const FPNG_DECODE_FAILED_DIMENSIONS_TOO_LARGE: _bindgen_ty_2 = 6;
pub const FPNG_DECODE_FAILED_CHUNK_PARSING: _bindgen_ty_2 = 7;
pub const FPNG_DECODE_FAILED_INVALID_IDAT: _bindgen_ty_2 = 8;
pub const FPNG_DECODE_FILE_OPEN_FAILED: _bindgen_ty_2 = 9;
pub const FPNG_DECODE_FILE_TOO_LARGE: _bindgen_ty_2 = 10;
pub const FPNG_DECODE_FILE_READ_FAILED: _bindgen_ty_2 = 11;
pub const FPNG_DECODE_FILE_SEEK_FAILED: _bindgen_ty_2 = 12;
pub type _bindgen_ty_2 = cty::c_int;
extern "C" {
    #[link_name = "\u{1}?fpng_get_info@fpng@@YAHPEBXIAEAI11@Z"]
    pub fn fpng_get_info(
        pImage: *const cty::c_void,
        image_size: u32,
        width: *mut u32,
        height: *mut u32,
        channels_in_file: *mut u32,
    ) -> cty::c_int;
}
